### ISSUE TITLE
Unable to run xelatex command

### ISSUE THREAD

**Issue by pseudo13** [saadq/resumake.io#103]
**Describe the bug**
Error "Unable to run xelatex command" appeared

**To Reproduce**
1. Installing of all packages
2. Fill in the needed information
3. Click on make to generate files
4. Error appears

**Expected behavior**
A pdf file get created.

**Comment by saadq** [comment]
Do you have `xelatex` installed on your machine? A few of the templates use `xelatex` or `lualatex` instead of `pdflatex` to compile the PDFs, so you need to install them separately. The [contributing.md](https://github.com/saadq/resumake.io/blob/master/contributing.md) needs to be updated to include this information.

**Comment by saadq** [comment]
Closing as issue is stale with no response.
