### ISSUE TITLE
LinkedIn Integration

### ISSUE THREAD

**Issue by Rob4001** [saadq/resumake.io#14]
Hey,
Love what you are doing, It would be brilliant if you could integrate with the LinkedIn API to automatically pull data from your profile. https://developer.linkedin.com/docs

**Comment by MatheusRV** [comment]
How can i help to do this integration?

**Comment by saadq** [comment]
I had started working on this on the [new](https://github.com/saadq/latexresu.me/tree/new) version of the site, but unfortunately LinkedIn requires you to apply for a partnership if you want to get any useful data from its API (without this partnership, you can only read stuff like basic profile info and current position, you don't get access to previous work experience, education, etc). 

Sadly, my application for the partnership was rejected without any reason why. I wrote a post in their support forums to ask for a reevaluation due to the fact that this app is open source and I met all the API eligibility criteria [here](https://developer.linkedin.com/legal/api-terms-of-use), but I'm not too hopeful about it.

This issue is just gonna be stuck for now unless I can somehow get accepted as a LinkedIn partner (if anyone has any inroads with LinkedIn employees, let me know! :p)

**Comment by saadq** [comment]
Closing due to the fact that it's currently impossible to do :(
