### ISSUE TITLE
Add Research & Publications

### ISSUE THREAD

**Issue by uttara-cmu** [saadq/resumake.io#15]
Love this website. It would be great to add Research and Publication section. I can download the source code and add this but will be incredibly convenient to have it on the website.

**Comment by aviral1701** [comment]
@saadq Can I work on it?

**Comment by aviral1701** [comment]
@saadq Any updates?

**Comment by saadq** [comment]
Hi @aviral1701, sorry for the delay I've been a bit busy with real life stuff. Sure, feel free to tackle this one.

**Comment by aviral1701** [comment]
@saadq No worries! Any word of advice for this one?

**Comment by saadq** [comment]
Hey @aviral1701. I'm very sorry for the long wait for my response. I've been having a lot going on (summer classes, part time work, brother's wedding) so I've been completely preoccupied. I most likely will not be very active in open-source stuff for about another 2 weeks.

After thinking about it, this issue is actually a pretty big amount of work. You would need to know React/Redux, adding a component in the [`sections`](https://github.com/saadq/latexresu.me/tree/master/app/client/src/components/sections) folder, and a [`fragment`](https://github.com/saadq/latexresu.me/tree/master/app/client/src/components/sections/fragments) for that section. This is just for the client-side. On the server side, you would need to first create the section in LaTeX for each template to see how it would look, and then write the `generateResearchSection()` for each template.

As mentioned, this is probably a lot of work so if you'd like to tackle different issues, that would be fine with me. And again, sorry about the wait! I definitely don't take contributors for granted and it's a delight having someone willing to help out with stuff.

**Comment by saadq** [comment]
`v3` is getting close to being finished. Once that is done, custom sections can be created which should handle this use case.
