### ISSUE TITLE
Unified Install Script of all OS's

### ISSUE THREAD

**Issue by pranavsambyal** [saadq/resumake.io#179]
**Problem**
I was trying to set this on a windows machine and faced different problems with it , Tried installing on Linux and everything started but errors were present in the server file with  led to some time wasted in troubleshooting. 

**What I propose**
An simple script that one can run from the main folder which set thing up for both client and server and also install required dependencies for the smooth function of the project.

If this is fascinate you the I can work on implementing the same in the project in order to make setup process easy for everyone who want to use It

**Comment by ducaale** [comment]
I recently found this self-contained LaTeX engine called [tectonic](https://github.com/tectonic-typesetting/tectonic). I think using it instead of pdfLaTeX should make it easier for people to run resumake.io locally. It is not a drop-in replacement for pdfLaTeX e.g I couldn't make a resume from the 8th template unless I remove the usage of letterspacing from the `microtype` package.

**Comment by saadq** [comment]
I have mostly setup v3 to be a server-side rendered website now using Next.js. Once I've got this setup fully done with the custom sections support migrated as well, I'm going to be tackling this issue to make lives easier for people.

@ducaale tectonic looks quite nice... template 8 is something i definitely don't want to drop support for since it's one of the more popular templates used by CS students. [It is the only template that uses `lualatex`](https://github.com/saadq/resumake.io/blob/main/app/server/src/generator/templates/index.js#L110) which I guess is why it doesn't quite work with with tectonic as-is. But if we can get it to work with the template it looks very promising and something I'm going to look into (and perhaps move all this to Docker https://github.com/rekka/tectonic-docker to make it even easier to setup)

**Comment by ducaale** [comment]
I have now checked all the templates with tectonic. So far, only template 8 and template 9 are incompatible with it. I can try to modify those templates so they can be compatible with tectonic. May I ask which branch you accept contributions from?

> (and perhaps move all this to Docker https://github.com/rekka/tectonic-docker to make it even easier to setup)

Wouldn't be easier to just install the tectonic binary instead of running docker?

**Comment by ducaale** [comment]
**Update**: I am currently experimenting with tectonic (self-contained LaTex engine in rust) and SwiftLaTex (LaTex compiled to wasm) to simplify the local development setup. The latter (i.e., SwiftLaTex) should also allow moving the pdf generation to the client-side.

**Comment by ducaale** [comment]
Oops, I didn't mean to close this issue. While replacing tectonic certainly simplifies the local setup required, we can do better and remove the required setup altogether by using SwiftLaTex (a wasm-powered LaTeX that should work in both the server and the client).

And because SwiftLaTex will allow us to move the PDF generation to the client-side, we get other benefits such as:
* Instant feedback when editing a resume
* Less compute bills for Resumake.io
* More Privacy for users creating a resume
* Unlike tectonic which only support XeTeX, SwiftLaTex supports both XeTeX and PDFLaTeX.

Currently, I am working on converting SwiftLaTeX to an npm package that could be easily installed. The plan is to support rendering the LaTeX in both the server and the client and let the user decide which option suits their needs.

**Comment by ducaale** [comment]
Support for client-side LaTeX generation has now landed in the main branch 🎉🎉🎉
