### ISSUE TITLE
Reorder Subelements (Skills, Jobs, etc.)

### ISSUE THREAD

**Issue by peterkos** [saadq/resumake.io#40]
I'd like to be able to change the order of skills and jobs without copying & pasting manually. Maybe also an option to sort them in chronological/reverse chronological order?

**Comment by saadq** [comment]
Yes, this would definitely be pretty convenient. Changing the order of the sections as a whole is possible in the new version, but your suggestion would be a nice feature to have. I'll look into the best way to try to implement this.

**Comment by dtsmith2001** [comment]
@saadq Perhaps the best way to do this is to offer several functional resumes, placing the skills, projects, education, and publications before experience. Re-arranging the sections for a template is easier than writing all that code to allow people to drag & drop or otherwise reorder.

It's also a nice way to give alternatives people want while you write all that code (assuming you want to write the code).

**Comment by saadq** [comment]
@dtsmith2001 The issue with that is I would have to account for a lot of different combinations of sections.

But I think you seem to be discussing changing the orders of the main sections themselves – that feature is already implemented:

![demo](https://user-images.githubusercontent.com/5678694/35769772-1fbe01a0-08de-11e8-8a1b-e37d63d6b0ee.gif)

I think this issue was mainly about changing the order of subelements in a section like changing the order of two school fields in the Education section.

**Comment by dtsmith2001** [comment]
Ah, I understand now. Very nice. I’ll now switch to your site for a functional resume. Thanks.

Thanks,
Dale Smith
dtsmith@mindspring.com
917-691-1791

Note: All times are Eastern.

**Comment by koshyviv** [comment]
Would love to see this feature

**Comment by nrgapple** [comment]
Was this ever merged?

**Comment by nrgapple** [comment]
this feature seems to be on the web site. can it be closed?

**Comment by peterkos** [comment]
@nrgapple I don't think the issue is solved yet, unless I am missing something.
The website lets you reorder the _sections_ (Education, Work, etc.) but this is about reordering specific elements within a section: like, reordering specific jobs.

**Comment by glacials** [comment]
+1 to this, to give a real use case:

I like to order my jobs from most recent to least recent. I recently switched jobs and wanted to add my new job to the top, so I opened my saved JSON file in Resumake and clicked "Add Job", but it appears at the bottom.

So if I want to get it to the top, I have to manually copy paste the sections in job A to job B, job B to job C, etc. so that the "job A" slot opens up for my new job to be in. This requires another tool to copy text between and is very tedious.

For others wanting an easier workaround to this issue, I recommend exporting to JSON and manually rearranging the sections in the `"work"` key. To add a new section, just add `{"highlights": []},` where you want it and it will be a blank job when you open it in Resumake.

**Comment by saadq** [comment]
This feature will be a part of the [v3](https://github.com/saadq/resumake.io/issues/63) rewrite

**Comment by saadq** [comment]
This has been implemented in v3. Hope to release within the next few weeks!

**Comment by powertrio77** [comment]
I don't see it, and I've moved my mouse on many areas, looking for click-to-drag. Also, I've tried Chrome, Firefox, and Edge with clear cache and I can't get Skills to Reorder. I can reorder the main sections (work or skills, example, it's great!)
1. Is this available in the Work section, to reorder the new job to the top? 
2. how to get the skills section to work, as seen in the video above?
Thanks for the post about using editing JSON, this is working. All good.

**Comment by adityag81** [comment]
+1

Any planned update on this (and v3)? Other than this, fantastic stuff!

**Comment by KarmaKami994** [comment]
How fare are we with implementing the re-ordering the subelements within the sections ?

ive read through the comments and saw it was tested but not released yet ?

**Comment by ducaale** [comment]
@KarmaKami994 It might take some time before v3 gets released with subelement re-ordering. In the meantime, you can export your resume as a JSON, do your edits and reimport it.
