### ISSUE TITLE
Add a template for GitHub issues

### ISSUE THREAD

**Issue by saadq** [saadq/resumake.io#56]
There's a guide on how to do this [here](https://help.github.com/articles/creating-an-issue-template-for-your-repository/). If anyone wants to do this, feel free :)

**Comment by alokpant** [comment]
Hey can I pick this issue? Do you already have a sample template in mind?

**Comment by saadq** [comment]
Sure @alokpant, feel free to take this issue! I don't really have any specific template in mind right now, but I would like to separate it into two possible things:

1. Is the user submitting a bug report?
2. Is the user submitting a feature request?

Maybe just have it split into two sections, and then ask the user to remove whichever section they aren't using. Take a stab at it and let me know if you have any questions. I'll also let you know if I have any comments if you submit an initial attempt!

**Comment by alokpant** [comment]
@saadq What do you think of instead of splitting it up into two sections, when user clicks on Issue they are allowed to select two options:
- Bugs
- Feature Request

This way, we can have two templates to serve purpose for each.

Github by default also provides templates for these, but I have modified bit to serve the purpose. Please review PR.

**Comment by saadq** [comment]
Actually just commented on the PR haha, but I like that approach much better!

**Comment by saadq** [comment]
Closed via #61.

**Comment by MatheusRV** [comment]
@saadq Now you could edit it visualy go to: https://github.com/saadq/resumake.io/issues/templates/edit
