### ISSUE TITLE
Allow the user to change resume background

### ISSUE THREAD

**Issue by z1333** [saadq/resumake.io#73]
First of, I love your site, thank you. I think it would be a good feature to be able to to change background (image or color). I edited the latex code for my resume and it made a huge difference as far as callbacks for jobs go. Once again thanks and keep up the great work

**Comment by saadq** [comment]
Hmm, not sure about this. Could you provide an example resume that has the background changed? I usually just see resumes as white backgrounds with dark text on it, not really familiar with colored backgrounds or backgrounds that have images on them.

**Comment by z1333** [comment]
[Resume1.pdf](https://github.com/saadq/resumake.io/files/2359814/Resume1.pdf)
[resume-5.pdf](https://github.com/saadq/resumake.io/files/2359815/resume-5.pdf)

**Comment by alexluong** [comment]
Is this something we want to pursue, @saadq? I'd be happy to help out in this feature.

**Comment by saadq** [comment]
Hey guys, I'm very sorry for the delay in my response @z1333. Also, I'm very grateful that you'd volunteer for this @alexluong! 

However, I'm not actually sure if I think this feature should be added to the app. I've looked at hundreds of resumes when trying to compile my list of templates, and I have almost never seen background images in them. I really wouldn't recommend anyone actually go through with it. I think with resumes it's always good to go with safe/boring vs being flashy/trying to stand out because there's a good chance that it could backfire. It's for this reason that a lot of the templates that Resumake uses have been modified to make them more "boring"/standard which I (personally) think is more professional (for example, template 2 is a modified version of [Awesome-CV](https://github.com/posquit0/Awesome-CV) without the random red highlights in the words).

I think for something like this it would probably be better to err on the side of caution because recruiters only spend _seconds_ looking a person's resume and you don't want to get taken less seriously because of an image you have in the background.

Sorry if my tone sounded judgmental to anyone – I personally don't have a problem with background images when used as more of a subtle texture like the first example that @z1333 gave. I just worry that recruiters won't feel the same way, or that people who are new to the whole resume thing may go overboard with the feature.
