### ISSUE TITLE
Inconsistency between Education and Work date period delimiter in Template 1

### ISSUE THREAD

**Issue by Sigurthorb** [saadq/resumake.io#74]
**Describe the bug**
Inconsistency in delimiter. Education uses '-' while work uses '|'

**To Reproduce**
1. Select template 1
2. Enter work date period and education date period
3. Generate (pdf or latex)
4. See difference between the splitter of the date periods

**Expected behavior**
The date periods would be consistent

**Desktop (please complete the following information):**
N/A

**Question**
Which would be desired? '-' or '|'?

**Comment by saadq** [comment]
Sorry for the delayed response! I think `-` is the most expected symbol, so I can update the generator to use that.

Or if you'd like to submit a PR that would be cool too. It would just be a matter of changing these lines:

https://github.com/saadq/resumake.io/blob/3c018004934137d3d501de5748fcf940527312ac/app/server/src/generator/templates/template1/index.js#L143-L145

and just changing the `|` to a `-`

Let me know if you'd be interested in fixing this, otherwise I can get it fixed soon.

**Comment by Sigurthorb** [comment]
Thank you for the response, I'll fix this and send in a PR
