### ISSUE TITLE
V3 TS-Node error

### ISSUE THREAD

**Issue by abhinavprateek** [saadq/resumake.io#75]
**Describe the bug**
TSError: ⨯ Unable to compile TypeScript

**To Reproduce**
1. Go to 'client folder'
2. Run 'npm install' and then 'npm start'
3. See error

**Expected behavior**
npm start should start the client side.

**Screenshots**
![snip_20180918154213](https://user-images.githubusercontent.com/8946513/45680787-7b4e1b80-bb59-11e8-947b-d8b42e1b5526.png)

**Comment by saadq** [comment]
Thanks for reporting this! Will look into it when I get home.

**Comment by abhinavprateek** [comment]
> Thanks for reporting this! Will look into it when I get home.

Any update?

**Comment by saadq** [comment]
Hey @abhinavprateek sorry for the delay! 

I think the issue is that `@types/webpack-dev-server` needs to be installed as a `devDependency` as well. I'm not sure why I'm not having this problem locally though...

Could you try running `npm install --save-dev @types/webpack-dev-server` and see if that fixes the problem?

As a side note, just note that `v3` is pretty much just a barebones scaffolded project right now, there isn't really anything in it. I don't think I'll be able to make much progress on it until winter break :/
